---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: MYCLAIM
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: external-MYTYPE-MYPROVIDER-binding-compatible
