#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: external-_type_-_provider_-binding-compatible
type: Opaque
stringData:
  type: $TYPE
  provider: $PROVIDER
  host: $HOST
  port: $PORT
  database: $DATABASE
  username: $USERNAME
  password: $PASSWORD