# stk-secret-reader.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stk-secret-reader
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bkstg-automation
  namespace: BACKSTAGE_TARGET_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkstg-automation
  labels:
    apps.tanzu.vmware.com/aggregate-to-app-operator-cluster-access: "true"
rules:
  - apiGroups: ["services.apps.tanzu.vmware.com"]
    resources: ["clusterinstanceclasses"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list", "patch", "update"]
  - apiGroups: ["services.apps.tanzu.vmware.com"]
    resources: ["classclaims"]
    verbs: ["*"]
  - apiGroups: ["services.apps.tanzu.vmware.com"]
    resources: ["resourceclaims"]
    verbs: ["*"]
  - apiGroups: ["servicebinding.io"]
    resources: ["servicebindings"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bkstg-automation
subjects:
  - kind: ServiceAccount
    name: bkstg-automation
    namespace: BACKSTAGE_TARGET_NAMESPACE
roleRef:
  kind: ClusterRole
  name: bkstg-automation
  apiGroup: rbac.authorization.k8s.io